meta:
  engine: 4.1.0
  author: Jakob Schmid
  version: 0.0.1
units:
  U: 19.05 # 19.05mm MX spacing
  u: 19 # 19mm MX spacing
  cx: 18 # 18mm Choc X spacing
  cy: 17 # 17mm Choc Y spacing
  stagger_ring: 15
  stagger_middle: 4
  stagger_index: -6
  stagger_inner: -5
points:
  key.spread: U
  key.padding: U
  zones:
    matrix_left:
      anchor:
        rotate: 5
      columns:
        outer:
        pinky:
        ring:
          key.stagger: stagger_ring
        middle:
          key.stagger: stagger_middle
        index:
          key.stagger: stagger_index
        inner:
          key.stagger: stagger_inner
      rows:
        bottom:
        home:
        top:
        num:
    thumbfan:
      anchor:
        ref: matrix_left_middle_bottom
        shift: [0, stagger_index-U]
      columns:
        near:
        home:
        far:
          key.stagger: stagger_inner
      rows:
        thumb:
    
  rotate: -20   

