meta:
  engine: 4.1.0
  author: Jakob Schmid
  version: 0.0.1
units:
  U: 19.05 # 19.05mm MX spacing
  u: 19 # 19mm MX spacing
  cx: 18 # 18mm Choc X spacing
  cy: 17 # 17mm Choc Y spacing
  px: U/2+5
  py: U/2+5
  stagger_ring: 15
  stagger_middle: 4
  stagger_index: -6
  stagger_inner: -5
  stagger_farfar: -2
  trrs_y_shift: -30
  reset_y_shift: -40
  trrs_jumper_y_shift: trrs_y_shift+6
points:
  key.spread: U
  key.padding: U
  zones:
    matrix_left:
      anchor:
        rotate: 0
        shift: [100, -150]
      columns:
        outer:
          key.col_net: P4
        pinky:
          key.col_net: P5
        ring:
          key:
            stagger: stagger_ring
            col_net: P6
        middle:
          key:
            stagger: stagger_middle
            col_net: P21
        index:
          key:
            stagger: stagger_index
            col_net: P20
        inner:
          key:
            stagger: stagger_inner
            col_net: P19
      rows:
        bottom:
          row_net: P16
        home:
          row_net: P14
        top:
          row_net: P15
        num:
          row_net: P18
    thumbfan:
      anchor:
        ref: matrix_left_middle_bottom
        shift: [0, stagger_index-U]
      columns:
        near:
          key.col_net: P6
        home:
          key.col_net: P21
        far:
          key:
            stagger: stagger_inner
            col_net: P20
        farfar:
          key:
            stagger: stagger_farfar
            col_net: P19
      rows:
        thumb:
          row_net: P10
outlines:
  raw:
    - what: rectangle
      where: true
      size: [U, U]
  board:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_left_outer_num
          shift: [-px, py]
        - ref: matrix_left_pinky_num
          shift: [U-px, py]
        - ref: matrix_left_ring_num
          shift: [-px, py]
        - ref: matrix_left_ring_num
          shift: [U-px, py]
        - ref: matrix_left_middle_num
          shift: [-px, py]
        - ref: matrix_left_middle_num
          shift: [px, py]
        - ref: matrix_left_index_num
          shift: [px-U, py]
        - ref: matrix_left_index_num
          shift: [px, py]
        - ref: matrix_left_inner_num
          shift: [px-U, py]
          # usb-c indent
        - ref: matrix_left_inner_num
          shift: [U-6, py]
        - ref: matrix_left_inner_num
          shift: [U-6, py-2]
        - ref: matrix_left_inner_num
          shift: [U+6, py-2]
        - ref: matrix_left_inner_num
          shift: [U+6, py]

        - ref: matrix_left_inner_num
          shift: [1.5U, py]
          # trrs indent
        - ref: matrix_left_inner_num
          shift: [1.5U, trrs_y_shift+6]
        - ref: matrix_left_inner_num
          shift: [1.5U-2, trrs_y_shift+6]
        - ref: matrix_left_inner_num
          shift: [1.5U-2, trrs_y_shift-6]
        - ref: matrix_left_inner_num
          shift: [1.5U, trrs_y_shift-6]

        - ref: thumbfan_farfar_thumb
          shift: [0.5U, py]
        - ref: thumbfan_farfar_thumb
          shift: [px, py]
        - ref: thumbfan_farfar_thumb
          shift: [px, -py]
        - ref: thumbfan_farfar_thumb
          shift: [-px, -py]
        - ref: thumbfan_far_thumb
          shift: [U-px, -py]
        - ref: thumbfan_far_thumb
          shift: [-px, -py]
        - ref: thumbfan_home_thumb
          shift: [U-px, -py]
        - ref: thumbfan_near_thumb
          shift: [-px, -py]
        - ref: thumbfan_near_thumb
          shift: [-px-U, -py]
        - ref: matrix_left_pinky_bottom
          shift: [U-px, -py]
        - ref: matrix_left_outer_bottom
          shift: [-px, -py]
      fillet: 0.999
  combo:
    part1:
      name: raw
    part2:
      name: board
      operation: stack
pcbs:
  no_hotswap:
    outlines:
      - outline: board
        layer: Edge.Cuts
    footprints:
      kailh_nothot:
        what: mx
        where: true
        params:
          keycaps: true
          reverse: true
          hotswap: false
          from: "{{col_net}}"
          to: "{{colrow}}"
      diode:
        what: diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]
      controller:
        what: promicro
        where: 
          ref: matrix_left_inner_num
          shift: [U, -6]
          rotate: -90
        params:
          orientation: "down"
      trrs_jack:
        what: my_trrs
        where:
          ref: matrix_left_inner_num
          shift: [U+6.5, trrs_y_shift]
          rotate: -90
        params:
          A: trrs_gnd
          B: trrs_sda # SDA
          C: P3 # SCL
          D: VCC
          my: true
      trrs_jumper_sda:
        what: my_threeway_jumper
        where:
          ref: matrix_left_inner_num
          shift: [U-3, trrs_jumper_y_shift]
          rotate: 90
        params:
          from: P2 # SDA
          to_a: trrs_sda
          to_b: trrs_gnd
          side: both
      trrs_jumper_gnd:
        what: my_threeway_jumper
        where:
          ref: matrix_left_inner_num
          shift: [U+3, trrs_jumper_y_shift]
          rotate: 90
        params:
          from: GND
          to_a: trrs_sda
          to_b: trrs_gnd
          side: both
      reset_button:
        what: my_button
        params:
          from: GND
          to: RST
          variant: 2_pin_th
        where:
          ref: matrix_left_inner_num
          shift: [U, reset_y_shift]
          rotate: -180
      i2c_sda_resistor:
        what: my_resistor
        params:
          from: P2
          to: VCC
        where:
          ref: matrix_left_inner_num
          shift: [U-6, reset_y_shift]
          rotate: 90
      i2c_scl_resistor:
        what: my_resistor
        params:
          from: P3
          to: VCC
        where:
          ref: matrix_left_inner_num
          shift: [U+6, reset_y_shift]
          rotate: 90
      rgb_1:
        what: my_ws2812
        params:
          din: P7
          dout: rgb_1_out
        where:
          ref: matrix_left_inner_num
          shift: [U, -50]
          rotate: 0
      rgb_2:
        what: my_ws2812
        params:
          din: rgb_1_out
          dout: rgb_2_out
        where:
          ref: matrix_left_inner_num
          shift: [U, -56]
          rotate: 0
      rgb_3:
        what: my_ws2812
        params:
          din: rgb_2_out
          dout: rgb_3_out
        where:
          ref: matrix_left_inner_num
          shift: [U, -62]
          rotate: 0
      rotary_encoder:
        what: rotary
        params:
          from: P5 # pinky col_net
          to: my_col_row
          A: P8
          B: GND
          C: P9
        where:
          ref: thumbfan_near_thumb
          shift: [-U, 2]
          rotate: 90
      scrollwheel:
        what: my_scrollwheel
        params:
          from: P5 # pinky col_net
          to: my_col_row
          A: P8
          B: P9
          C: GND
          D: '' # unused
          orientation: down
        where:
          ref: thumbfan_near_thumb
          shift: [-U-0.5, 0]
          rotate: 90
      rotary_diode:
        what: diode
        params:
          from: my_col_row
          to: P10 # thumb row net
        where:
          ref: thumbfan_near_thumb
          shift: [0, U/2-stagger_index/2]
          rotate: 180


          

